name: Cypress Tests

on:
  push:
    branches:
      - main # Adjustesttttttttttttttttttttt the branch name as needed

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npm run cypress:run # Adjust this script to match your project setup

    - name: Upload results to Cypress Dashboard
      run: npx cypress-ci upload

# This is just a basic example; you may need to adjust it to fit your project's specific setup
